### PR TITLE
Updated Ruby folder location in docs.

### PR DESCRIPTION
**Pull request by mtortonesi**
Updated documentation to reflect changes in location of Ruby folder within the GraalVM project layout (in version 0.27 the "language" folder was moved to "jre/languages").

### CODE REVIEW

**Comment by chrisseaton** [comment]
Thanks for the contribution.

**Comment by chrisseaton** [comment]
Is that a not-sign in your commit message '¬'? What does that mean?

**Comment by mtortonesi** [comment]
2017-09-05 12:00 GMT+02:00 Chris Seaton <notifications@github.com>:

> Is that a not-sign in your commit message '¬'?
>
Yes, indeed.


> What does that mean?
>
It is a typo. I am very sorry about it.




-- 
Mauro Tortonesi, Ph.D.

Assistant Professor
Distributed Systems Research Group
Engineering Department
University of Ferrara

**Comment by chrisseaton** [comment]
Ok no problem!

**Pull request merged**
