### PR TITLE
Add an integration test verifying there is no extra output

### PR DESCRIPTION
**Pull request by eregon**

### CODE REVIEW

**Comment by pitr-ch** [comment]
if this was merged without approval, it should say so here and a reason should be included.

**Comment by eregon** [comment]
This was critical for the release so I could not delay it anymore.
Furthermore, it's an extra test, not changing any logic.

**Comment by eregon** [comment]
(Please comment/review if you would like though)

**Comment by chrisseaton** [comment]
I think the point was to just comment on issues that you are about to force merge with "Force merging because...".

**Pull request merged**
