### PR TITLE
Deprecate jt run and prefer jt ruby

### PR DESCRIPTION
**Pull request by eregon**
* jt run leaves the jt process alive and adds another process in between,  which is not needed if running TruffleRuby from the command line.
* jt run is only useful internally when TruffleRuby must be invoked  multiple times.
* Also remove references to JRuby in jt.rb.

### CODE REVIEW

**Comment by nirvdrum** [comment]
This one is going to take a lot of effort for me to retrain. I never use `jt ruby` and find it an awkwardly named command.

**Comment by chrisseaton** [comment]
I didn't know there was a difference between `run` and `ruby`. If we want to get rid of the semantic difference (I don't think I've been depending on it) that's fine, but like Kevin I'm not going to agree to getting rid of the name.

**Comment by nirvdrum** [comment]
I think the warning and deprecation are perhaps a bit too strong. In particular, deprecation implies eventual removal. And I think we just have too many examples floating around on the Internet using `jt run` to merit getting rid of it. I'd rather just hide it from the "help" command update references to use `jt ruby`.

**Comment by eregon** [comment]
OK, I removed the warning.
But please use `jt ruby`, I believe it's more intuitive to external contributors than `jt run` and says what command is run.

**Pull request merged**
