### PR TITLE
Fix RB_WAITFD_IN macro comment

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by chrisseaton** [comment]
How did this get past the gate originally?

**Comment by eregon** [comment]
This is simply not used/tested I guess. Only in outside gems.

**Comment by chrisseaton** [comment]
But this header is used when we build `openssl` isn't it? It's the basic Ruby header, and isn't this a pre-processor syntax error?

**Comment by eregon** [comment]
It's not a preprocessor syntax error, the preprocessor replaces usages of the macro (they are none)
with `0x001 # TODO BJF 6-Aug-2017 Implement the correct value`, which is likely invalid C but since it's never used it doesn't trigger any problem. Try with `cc -E foo.c` if you are curious.

**Comment by bjfish** [comment]
@chrisseaton I didn't see an error until trying to compile the mysql2 gem which uses this macro.

**Pull request merged**
