### PR TITLE
Add included gems into the default_specifications_dir

### PR DESCRIPTION
**Pull request by bjfish**
This should help to activate gems which are bundled. E.g.
```
irb(main):001:0> gem "json"
=> true
irb(main):002:0> gem "rake"
=> true
irb(main):003:0> gem "rdoc"
=> true
irb(main
```

### CODE REVIEW

**Comment by eregon** [comment]
Looks good but the JSON gemspec should not show as a binary file.
I had a look and there are some NULL bytes in there, which is why it shows as a "binary" files.
The minitest gemspec does not have them, so I assume it's a bug.
```ruby
start_of_json_gemspec = "# -*- encoding: utf-8 -*-\n# stub: json 1.8.3 ruby lib\n# stub: ext/json/ext/generator/extconf.rb\u0000ext/json/ext/parser/extconf.rb\u0000ext/json/extconf.rb\n\nGem::Specification.new do |s|\n "
```

**Comment by bjfish** [comment]
@eregon I noticed the NULL bytes in there too. I intentionally left the null bytes there. My reasoning was that all the gemspecs for the json gem appear to have these NULL bytes intentionally. I'm not sure why.  So, I thought it best to preserve the original gemspec file as long as it doesn't seem to be causing any issues.

I notice some text editors are still able to view these files fine but others not.

**Comment by eregon** [comment]
I think it's some bug due to packaging that gem on a very old Ruby or Rubygems version or so.
I would remove it since we check it in, and unreadable binary files are no good.

**Comment by bjfish** [comment]
@eregon I've searched a little more. The null byte definitely looks intentional:
https://github.com/ruby/ruby/blob/trunk/lib/rubygems/specification.rb#L2475
https://www.bountysource.com/issues/1649408-use-different-separator-then-0-for-stub-line
https://github.com/rubygems/rubygems/commit/652e31942e807ae4625d2cc1eb771cd296c8d1ed

I think this design is unfortunate from a tooling perspective but I am still inclined to leave it as is because it appears to how this is currently designed.  FWIW it looks like Github fileviewer, IntelliJ, Text Wrangler and other tools are still able to display these. Thoughts?

**Comment by eregon** [comment]
@bjfish Thanks for looking, so this only happens if there are more than 1 `require_paths` or more than 1 native `extensions`, which is only the case of `json` here with 3 native extensions.
I agree with you, as this is intended (even though unfortunate) we should keep the file as it is.

**Comment by eregon** [comment]
Could we have a test for this to make sure it works? Maybe a spec under spec/truffle.

**Comment by bjfish** [comment]
@eregon yes, I've added a spec

**Pull request merged**
