### PR TITLE
Rename executeVoid so the DSL does not generate useless methods

### PR DESCRIPTION
**Pull request by eregon**
* Reduces the number of runtime compilable methods by ~1100
  and the image size by ~1MB.

### CODE REVIEW

**Comment by chrisseaton** [comment]
I think `unusedReturnValueExecute` is a pretty cumbersome name. I also think it should start with `execute...` as that's the convention - or is that required for the PR to work? How about `executeNoReturnValue`?

**Comment by eregon** [comment]
I'm happy with another name, do you have ideas?
It *is* required to not start with `execute` as the comment says, so the DSL doesn't think it should generate methods for it.

**Comment by chrisseaton** [comment]
How about `doExecuteVoid`?

**Comment by chrisseaton** [comment]
We also need to comment this or test it so we don't rename and regress. How about a subclass with `final executeVoid` for all DSL nodes?

**Comment by eregon** [comment]
It's already commented in `RubyNode`, but I'll change it to JavaDoc to be a bit more prominent.
A subclass seems a lot of work and changes and not really worth it here.

**Comment by eregon** [comment]
Changed to `doExecuteVoid()`.

**Pull request merged**
