### PR TITLE
Native platform option

### PR DESCRIPTION
**Pull request by eregon**
It's actually fairly easy to boot without NFI.
We can even output to STDOUT with polyglot streams!

RubyGems and patching must be disabled though as they do many native calls.

### CODE REVIEW

**Comment by pitr-ch** [comment]
This is nice, but it should be tested somewhere.

**Comment by chrisseaton** [comment]
@pitr-ch there's an integration test now.

**Comment by eregon** [comment]
See 7fa46e5, that was there since I opened the PR.

**Comment by pitr-ch** [comment]
Great thanks!

**Pull request merged**
