### PR TITLE
Give up on Travis

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by nirvdrum** [comment]
Do we need to update https://github.com/graalvm/truffleruby/blob/master/lib/truffleruby-tool/lib/actionpack_exclusions.yaml as well?

**Comment by chrisseaton** [comment]
I just changed it to be past-tense. They still need a fresh look but I'm not going to do that as part of this PR.

**Comment by chrisseaton** [comment]
What do @bjfish, @pitr-ch  and @aardvark179 think?

**Comment by bjfish** [comment]
@chrisseaton I think it's okay to remove travis CI if these CI jobs are being duplicated other CI jobs.

**Comment by eregon** [comment]
@bjfish yes, all that Travis tests is also tested by `CI/` jobs.

**Comment by pitr-ch** [comment]
👍

**Comment by eregon** [comment]
Maybe CircleCI is a better alternative for us in the future, they seem to have good Docker support and they support debugging via SSH.

**Pull request merged**
