### PR TITLE
Faster Process specs

### PR DESCRIPTION
**Pull request by eregon**

### CODE REVIEW

**Comment by eregon** [comment]
This seems to help a bit but it's not clear with Travis big variations.
Maybe we should just run core specs (or the slow ones) on CI and not Travis since there it's fast enough?

**Comment by chrisseaton** [comment]
We could just not run process specs I think and that would make a big difference.

**Comment by eregon** [comment]
We could try that, but on my system Process specs only take 1 min 30 seconds.

**Comment by eregon** [comment]
I think we should merge the current changes, it makes working with the Process specs locally much nicer, and should help the CI a little.

**Pull request merged**
