### PR TITLE
Remove old launchers

### PR DESCRIPTION
**Pull request by chrisseaton**
@graalvm/truffleruby was anyone using any of these launchers?

### CODE REVIEW

**Comment by eregon** [comment]
rake/rdoc/ri etc should still work at least with `bin/truffleruby -S ri Array`, do they?

**Comment by eregon** [comment]
I think it's better to remove launchers and stdlib binaries separately (at least in commits).

**Comment by chrisseaton** [comment]
I started to do that, but then realised the stdlib binaries referenced `env jruby`, which would never have been working anyway.

**Comment by chrisseaton** [comment]
I've rolled back just to remove the legacy names for our launcher.

I should write a set of tests that all the remaining launchers work as intended.

**Pull request merged**
