### PR TITLE
Support making a distribution with Graal and JVMCI

### PR DESCRIPTION
**Pull request by eregon**
* About 80MB in size for the .tar.gz and ~250MB uncompressed.

### CODE REVIEW

**Comment by chrisseaton** [comment]
I thought we already had a PR go in for making a minimal distribution?

**Comment by eregon** [comment]
This is no longer minimal, since it supports now 4 configurations:
`minimal`, `sulong`, `graal` and `full` (sulong+graal).

Basically the full distribution should fix #118, but is currently only working on Linux.
For macOS, I am not aware of any way to get a OpenJDK with JVMCI (so that we can redistribute it without click-through).

> Please write up how to use this in the `doc/user`.

What should I document? How to use it?
Similar to the [release text](https://github.com/graalvm/truffleruby/releases)?

**Comment by chrisseaton** [comment]
I mean document that this is something that you can do, and how to build it - that just documents how to use it.

**Comment by eregon** [comment]
> I mean document that this is something that you can do, and how to build it - that just documents how to use it.

Then that should be under `doc/contributor`, right? I don't intended for end-users to run this script, but rather download the release tarball and use it.

**Comment by eregon** [comment]
@chrisseaton Documentation added. I added both user and contributor docs.

**Pull request merged**
