### PR TITLE
Add parsing/translation/execution metrics

### PR DESCRIPTION
**Pull request by eregon**
Makes it easier to spot what takes time during startup in details.

### CODE REVIEW

**Comment by nirvdrum** [comment]
Looks good. I think the the parsing metrics should be included in the default time metrics. I can appreciate you didn't want the booleans to get too messy, but I think you can fix that easily enough by setting `-Xmetrics.time.parsing=true` in `metrics_time` in jt.rb.

**Comment by eregon** [comment]
> I think the the parsing metrics should be included in the default time metrics.

One problem is `parsing` appears both as nested in `load-core` and in `post-boot`, and I think the records for the benchmarking don't handle that. It's not a problem in the textual output though.

**Comment by nirvdrum** [comment]
Okay. I leave it up to you then. Maybe we can just add a flag to disable parsing stats. And add another to enable per-file. I just know I'm never going to remember `-Xmetrics.time.parsing=true` and it's something I think is useful to see when I run `jt metrics time` locally.

**Comment by eregon** [comment]
> Maybe we can just add a flag to disable parsing stats. And add another to enable per-file. 

That's the current state, two flags: to enable parsing stats, and to enable parsing stats per file.
I'll take a look if it's easy to integrate with the benchmarking.

**Comment by nirvdrum** [comment]
I meant flags to `jt metrics time`. E.g., `jt metrics time --no-parse` (for benchmarks) and `jt metrics time --per-file` for parsing per file. Or something along those lines.

**Comment by eregon** [comment]
@nirvdrum I compromised and parsing metrics are enabled for `core` by default now.
This works around the benchmarking problem.
I think it's fair to use
```
jt metrics time -Xmetrics.time.parsing.file=true -e '0'
```
when one wants detailed metrics per file, I'd rather not add code to `jt` when not needed.

**Comment by nirvdrum** [comment]
I think the benefit in adding it as a flag to `jt metrics time` is it's documented in `jt help`. You'd have to know to look for TruffleRuby options to enable this extra metric. But I can appreciate not wanting to complicate `jt`.

**Pull request merged**
