### PR TITLE
Add a script to create a minimal pre-built distribution of TruffleRuby

### PR DESCRIPTION
**Pull request by eregon**

### CODE REVIEW

**Comment by pitr-ch** [comment]
The file should probably have a more self-descriptive name.

**Comment by eregon** [comment]
@pitr-ch Any suggestion?
It's basically the `install` step of `make install`, that is copying only the needed files to a given prefix, and it additionally makes a .tar.gz of it.

**Comment by pitr-ch** [comment]
I rather have something like `package-graal-less-testing-distribution`, I would have never guessed the connection with `make install`.

**Comment by eregon** [comment]
I renamed it to `tool/make-testing-distribution.sh`.

**Pull request merged**
