### PR TITLE
Upgrade the version of asciidoctor used for benchmarks because the previous had a dependency on a version of the 'yard' gem with a security vulnerability.

### PR DESCRIPTION
**Pull request by nirvdrum**

### CODE REVIEW

**Comment by eregon** [comment]
Is `yard` actually used in those benchmarks? If it's only a development dependency I think it would be fine to ignore it.

**Comment by chrisseaton** [comment]
We still need to get security warnings with this update.

https://github.com/graalvm/truffleruby/network/dependencies#30353477

**Comment by nirvdrum** [comment]
The nokogiri one wasn't showing before. I upgraded to the latest released version of asciidoctor. I think we'll have to deal with it upstream.

**Comment by eregon** [comment]
The updated version still depends on yard 0.9.8 (fixed in 0.9.11 according to GitHub), and this PR did not seem to change that.
https://github.com/graalvm/truffleruby/blob/master/bench/asciidoctor/asciidoctor/asciidoctor.gemspec#L45
It's also clearly a development dependency, and benchmarks cannot possibly use yard since there is no yard files under `bench`. So I'd be for reverting this change and ignoring the non-relevant security warning about yard.

**Pull request merged**
