### PR TITLE
Rename projects and suite in Mx

### PR DESCRIPTION
**Pull request by eregon**

### CODE REVIEW

**Comment by eregon** [comment]
Should we rename the distributions jar/zip as well to TRUFFLERUBY.jar and TRUFFLERUBY-ZIP.zip instead of RUBY.jar and RUBY-ZIP.zip ?

**Comment by chrisseaton** [comment]
I think so.

**Comment by eregon** [comment]
Done, feel free to merge when it's best.

**Comment by eregon** [comment]
Rebased, we should merge this soon.

**Comment by chrisseaton** [comment]
I'll do it on Monday when I can ask the right people to create the new repo.

**Pull request merged**
