### PR TITLE
Allow to set TRUFFLERUBY_CEXT_ENABLED=false to not build cexts with mx build

### PR DESCRIPTION
**Pull request by eregon**
* Consider TRUFFLERUBY_CEXT_ENABLED=false as disabled in patches as well.

### CODE REVIEW

**Comment by chrisseaton** [comment]
Should the variable perhaps be called `TRUFFLERUBY_CEXT_DISABLED`? At the moment you disable C extensions by setting `TRUFFLERUBY_CEXT_ENABLED` (to `false`, but still).

**Comment by eregon** [comment]
Then it might be weird to install gems with cexts (which is currently not default), as you would need:
```
TRUFFLERUBY_CEXT_DISABLED=false
```
which is a double negation.

**Comment by chrisseaton** [comment]
Yes, so it'd be `TRUFFLERUBY_CEXT_DISABLED=true`. If you don't set `TRUFFLERUBY_CEXT_DISABLED`, or set `TRUFFLERUBY_CEXT_DISABLED=false`, they're enabled. At the moment not setting `TRUFFLERUBY_CEXT_ENABLED` enables them.

**Comment by eregon** [comment]
That would build gem cexts by default, which is problematic as it could prevent `bundle install` to succeed and sometimes even prevent things we would be fine without cexts (because there is a pure-ruby fallback, or because that gem is not actually used).

Can we merge this and discuss defaults separately?

**Pull request merged**
