### PR TITLE
Tidy some thing in specs

### PR DESCRIPTION
**Pull request by chrisseaton**
@nirvdrum did you say that the old formatter was unused and probably not working? Let's remove it if it is.

### CODE REVIEW

**Comment by nirvdrum** [comment]
The report actually works still with a 2 line diff. As it turns out, we don't need maven -- we can just use ant by using the buildTestReports.xml file that this PR deletes.

**Comment by chrisseaton** [comment]
Do you want to keep it? I mean we're not using it for anything? No that it wasn't useful and valuable, and we can get it back if we start using it again. But at the moment it's just dead code.

**Comment by nirvdrum** [comment]
The utility of it has definitely dropped off since we now run most of the specs. I usually only reference it when conference season rolls around. I think its biggest value at the moment could be in easily seeing which specs take the longest. But I can look at packaging it up into its own gem then, too.

**Comment by eregon** [comment]
FWIW `mspec -fp` can easily show times taken by each example and `describe` group

**Pull request merged**
